name: dashlist
description: Shopping list application

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  dashlist_theme: 
    path: ../dashlist_theme
  flutter:
    sdk: flutter
  flutter_json_view: ^0.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  freezed_annotation: ^0.14.3
  gap: ^2.0.0
  http: ^0.13.3
  mercure_client: ^1.0.1
  path_to_regexp: ^0.4.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^5.0.2
  mocktail: ^0.2.0
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
