version: "3.4"

services:
  php:
    container_name: php
    build:
      context: ./api
      target: api_platform_php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      APP_ENV: dev
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  consumer:
    container_name: consumer
    build:
      context: ./api
      target: api_platform_php
    entrypoint: docker-php-entrypoint
    command: bin/console messenger:consume
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      APP_ENV: dev
    healthcheck:
      test: ['CMD', 'ps', 'aux', '|', 'egrep', '"\d+:\d+ php bin/console messenger:consume"']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  caddy:
    container_name: caddy
    build:
      context: api/
      target: api_platform_caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
      MERCURE_EXTRA_DIRECTIVES: demo /srv/mercure-assets/
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  database:
    container_name: database
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_PASSWORD=psw
      - POSTGRES_USER=herveGuigoz
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
  
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: rmsoft
    ports:
      - '8999:8080'
    depends_on:
      - database

volumes:
  php_socket:
  db_data:
  caddy_data:
  caddy_config:
