version: "3.4"

services:
  php:
    container_name: cocook_php
    build:
      context: ./api
      target: api_platform_php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  consumer:
    container_name: cocook_consumer
    build:
      context: ./api
      target: api_platform_php
    entrypoint: docker-php-entrypoint
    command: bin/console messenger:consume
    depends_on:
      - database
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'ps', 'aux', '|', 'egrep', '"\d+:\d+ php bin/console messenger:consume"']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  caddy:
    container_name: cocook_caddy
    build:
      context: api/
      target: api_platform_caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  database:
    container_name: cocook_database
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=cocook
      - POSTGRES_PASSWORD=psw
      - POSTGRES_USER=herveGuigoz
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw
  
  adminer:
    container_name: cocook_adminer
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: rmsoft
    ports:
      - '8999:8080'
    depends_on:
      - database

volumes:
  php_socket:
  db_data:
  caddy_data:
  caddy_config:
