name: dashlist_theme
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.3
  google_fonts: ^2.1.0
  path_icon: ^0.7.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.5

flutter: