name: dashlist_theme
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.3
  gap: ^2.0.0
  google_fonts: ^2.1.0
  path_icon: ^0.7.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.5

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic